# Generated by Django 5.2.1 on 2025-06-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.document'),
        ),
    ]
