# Generated by Django 5.2.1 on 2025-06-03 16:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_course_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.FileField(null=True, upload_to=core.models.course_document_file_path),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
