# Generated by Django 5.2.1 on 2025-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
